### ISSUE TITLE
User can complete an order

### ISSUE THREAD

**Issue by kimberly-bird** [talkative-tangs/Bangazon-LLC-2#2]
_**Given** the user is authenticated
**And** the user is viewing their open order
**When** the user clicks the *Complete Order* button
**Then** the user should be presented with a view that allows them to select a payment type for the order_

**Given** the user selects a payment option
**When** the user clicks the *Done* button  
**Then** the payment type must be added to the order
**And** the user will be presented with a confirmation/thank you screen

**Comment by laboyd001** [comment]
User is now able to add items to their cart, select payment type and complete an order.  User when logged out is directed to login and then when user logs in they are redirected back to cart so they can complete the order.
