### ISSUE TITLE
User can delete a payment type

### ISSUE THREAD

**Issue by kimberly-bird** [talkative-tangs/Bangazon-LLC-2#9]
**Given** the user is authenticated
**When** the user performs a gesture on the *My Settings* hyperlink in the navigation bar
**And** the user clicks on *Payment Options*
**And** the user clicks on the *Delete* hyperlink next to a payment type
**Then** the payment option will get deleted

> Python students only, here's a tip: https://github.com/makinacorpus/django-safedelete/blob/master/safedelete/models.py

**Comment by laboyd001** [comment]
User is now able to delete a payment type from the payment options page in my account.  Payment options is now accessed through a payment options button on the my account page.
